window.dataLayer = window.dataLayer || [];

const products = [
  {id:'p001',name:'Eco Smart Lamp',price:1290,category:'Home Tech',desc:'A minimal smart lamp for desks, bedside tables and cozy corners.',art:'LAMP'},
  {id:'p002',name:'Pocket Power Bank',price:1790,category:'Gadgets',desc:'Compact everyday backup power with a clean, travel-friendly design.',art:'POWER'},
  {id:'p003',name:'Wireless Mini Speaker',price:2190,category:'Audio',desc:'A small wireless speaker made for everyday listening.',art:'SOUND'},
  {id:'p004',name:'USB-C Hub Pro',price:2490,category:'Accessories',desc:'A practical multi-port hub for your laptop and work setup.',art:'HUB'},
  {id:'p005',name:'AirFlow Desk Fan',price:1590,category:'Home Tech',desc:'Quiet desk airflow with a compact footprint.',art:'AIR'},
  {id:'p006',name:'Focus Timer',price:990,category:'Desk',desc:'A simple visual timer for focused work sessions.',art:'TIME'}
];

function pushEvent(eventName, params={}) {
  window.dataLayer.push({event:eventName,...params});
  console.log('[dataLayer]', eventName, params);
}
function money(n){return '৳'+Number(n).toLocaleString('en-BD')}
function getCart(){return JSON.parse(localStorage.getItem('ecotech_cart')||'[]')}
function saveCart(cart){localStorage.setItem('ecotech_cart',JSON.stringify(cart));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('#cartCount').forEach(el=>el.textContent=n)}
function addToCart(id,qty=1){const p=products.find(x=>x.id===id);if(!p)return;const cart=getCart();const item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});saveCart(cart);pushEvent('add_to_cart',{ecommerce:{currency:'BDT',value:p.price*qty,items:[{item_id:p.id,item_name:p.name,price:p.price,quantity:qty}]}});alert(p.name+' added to cart.');}
function removeFromCart(id){const cart=getCart();const item=cart.find(x=>x.id===id);const p=products.find(x=>x.id===id);saveCart(cart.filter(x=>x.id!==id));if(item&&p)pushEvent('remove_from_cart',{ecommerce:{currency:'BDT',value:p.price*item.qty,items:[{item_id:p.id,item_name:p.name,price:p.price,quantity:item.qty}]}});renderCart()}
function cartDetails(){return getCart().map(i=>({...i,product:products.find(p=>p.id===i.id)})).filter(x=>x.product)}
function cartTotal(){return cartDetails().reduce((s,i)=>s+i.product.price*i.qty,0)}
function renderProducts(list=products){const grid=document.getElementById('productGrid');if(!grid)return;grid.innerHTML=list.length?list.map(p=>`<article class="product-card"><a href="product.html?id=${p.id}" data-product="${p.id}"><div class="product-art">${p.art}</div></a><div class="product-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="small-btn" data-add="${p.id}">Add to cart</button></div></div></article>`).join(''):'<div class="empty">No products found.</div>';grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();addToCart(b.dataset.add)}));grid.querySelectorAll('[data-product]').forEach(a=>a.addEventListener('click',()=>{const p=products.find(x=>x.id===a.dataset.product);if(p)pushEvent('select_item',{ecommerce:{items:[{item_id:p.id,item_name:p.name,price:p.price}]}})}))}
function renderProductDetail(){const el=document.getElementById('productDetail');if(!el)return;const id=new URLSearchParams(location.search).get('id')||'p001';const p=products.find(x=>x.id===id)||products[0];pushEvent('view_item',{ecommerce:{currency:'BDT',value:p.price,items:[{item_id:p.id,item_name:p.name,item_category:p.category,price:p.price}]}});el.innerHTML=`<div class="detail"><div class="detail-art">${p.art}</div><div><p class="eyebrow">${p.category}</p><h1>${p.name}</h1><p>${p.desc}</p><h2>${money(p.price)}</h2><button class="btn primary" id="detailAdd">Add to cart</button></div></div>`;document.getElementById('detailAdd').addEventListener('click',()=>addToCart(p.id))}
function renderCart(){const area=document.getElementById('cartArea');if(!area)return;const items=cartDetails();pushEvent('view_cart',{ecommerce:{currency:'BDT',value:cartTotal(),items:items.map(i=>({item_id:i.product.id,item_name:i.product.name,price:i.product.price,quantity:i.qty}))}});if(!items.length){area.innerHTML='<div class="cart-box empty">Your cart is empty.<br><br><a class="btn primary" href="index.html#shop">Browse products</a></div>';return}area.innerHTML=`<div class="cart-box">${items.map(i=>`<div class="cart-row"><div><strong>${i.product.name}</strong><div>${i.qty} × ${money(i.product.price)}</div></div><div><strong>${money(i.product.price*i.qty)}</strong><br><button class="small-btn" data-remove="${i.product.id}">Remove</button></div></div>`).join('')}<div class="cart-row"><strong>Total</strong><strong>${money(cartTotal())}</strong></div><div class="cart-actions"><a class="btn primary" href="checkout.html">Proceed to checkout</a><a class="btn ghost" href="index.html#shop">Continue shopping</a></div></div>`;area.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeFromCart(b.dataset.remove)))}
function renderCheckout(){const s=document.getElementById('checkoutSummary');const items=cartDetails();if(!s)return;if(!items.length){s.innerHTML='<div class="empty">Your cart is empty. <a href="index.html#shop">Go shopping</a></div>';return}s.innerHTML=`<strong>Order summary</strong>${items.map(i=>`<div class="cart-row"><span>${i.product.name} × ${i.qty}</span><span>${money(i.product.price*i.qty)}</span></div>`).join('')}<div class="cart-row"><strong>Total</strong><strong>${money(cartTotal())}</strong></div>`;pushEvent('begin_checkout',{ecommerce:{currency:'BDT',value:cartTotal(),items:items.map(i=>({item_id:i.product.id,item_name:i.product.name,price:i.product.price,quantity:i.qty}))}});const form=document.getElementById('checkoutForm');form?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const orderId='ECO-'+Date.now().toString().slice(-8);localStorage.setItem('ecotech_last_order',JSON.stringify({orderId,...data,total:cartTotal(),items}));pushEvent('purchase',{ecommerce:{transaction_id:orderId,currency:'BDT',value:cartTotal(),items:items.map(i=>({item_id:i.product.id,item_name:i.product.name,price:i.product.price,quantity:i.qty}))}});localStorage.removeItem('ecotech_cart');location.href='thank-you.html'})}
function renderThankYou(){const details=document.getElementById('orderDetails');if(!details)return;const order=JSON.parse(localStorage.getItem('ecotech_last_order')||'null');if(order){document.getElementById('orderMessage').textContent='Demo order '+order.orderId+' has been placed. No real payment was processed.';details.innerHTML=`<div class="checkout-summary"><div class="cart-row"><strong>Order ID</strong><span>${order.orderId}</span></div><div class="cart-row"><strong>Total</strong><span>${money(order.total)}</span></div></div>`}}
function setupContact(){const form=document.getElementById('contactForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));pushEvent('generate_lead',{lead_type:'contact_form',email:data.email});document.getElementById('contactStatus').textContent='Message submitted successfully (demo).';form.reset()})}
function setupSearch(){const input=document.getElementById('searchInput');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();pushEvent('search',{search_term:q});renderProducts(products.filter(p=>(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(q)))})}
function init(){updateCartCount();pushEvent('page_view',{page_location:location.href,page_title:document.title});const page=document.body.dataset.page;if(page==='home'){renderProducts();setupSearch()}if(page==='product')renderProductDetail();if(page==='cart')renderCart();if(page==='checkout')renderCheckout();if(page==='thankyou')renderThankYou();if(page==='contact')setupContact();}
document.addEventListener('DOMContentLoaded',init);
